title: Somnium Wiki
description: Somnium Wiki
theme: just-the-docs
#remote_theme: just-the-docs\just-the-docs
back_to_top: true
back_to_top_text: "Back to top"
color_scheme: ???

url: https://wiki.scenicroute.games/

# Pages in following directories will be excluded from the Export
exclude:
  - wip/

search:
  heading_level: 4
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; CHANGETHIS."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

aux_links:
  "Patreon":
    - "https://www.patreon.com/scenicroutegames"
  "Download":
    - "https://www.scenicroute.games/projects/somnium"
  "News":
    - "https://www.scenicroute.games/blog-posts/current-news"
  "Discord":
    - "https://discord.com/invite/nAQWr4VmG6"    
    
    
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/apoapse1/scenicroute.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
   
callouts_level: loud
callouts:
  highlight:
    title: Notice
    color: yellow
  important:
    title: Important
    color: yellow
  logfile:
    title: Log Section
    color: green
  iniSetting:
    title: INI Setting
    color: green
  alternative:
    title: Alternative
    color: green
  console:
    title: Console Commands
    color: green    
  hint:
    title: Hint
    color: green  
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red
  NoTitleYellow:
    color: yellow
  NoTitleGreen:
    color: green
    
# Define Jekyll collections
collections:
  # Define a collection named "ClassGuides", its documents reside in the "_ClassGuides" directory
  01-Support:
    permalink: "/:collection/:path/"
    output: true
  02-Gameplay&Features:
    permalink: "/:collection/:path/"
    output: true
 
   
just_the_docs:
  collections:
    01-Support:
      name: Support Pages
      nav_fold: true   
    02-Gameplay&Features:
      name: Gameplay and Features
      nav_fold: true   
    




nav_external_links:
#  - title: Requiem WIKI [Reddit]
#    url: https://www.reddit.com/r/skyrimrequiem/wiki/index
#    hide_icon: false # set to true to hide the external link icon - defaults to false
     
    
# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-DSSX8SK5DC
#ga_tracking_anonymize_ip: nil  # Use GDPR compliant Google Analytics settings (true/nil by default)
